Repository MahmoudRe/JetBrainsPlugin, pull requests merged in 2020-04, with the labels that each got.

#4 Initial project for the JetBrains Plugin.
  .gitignore
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/PopupDialogAction.java
  src/main/resources/META-INF/plugin.xml
Labels: Initialization

#7 [feature] initial example class that can be used to test the plugin on.
  src/main/java/ExampleClasses/ExampleClassFourMethods.java
Labels: Initialization

#12 [feat] Analyze method
  src/main/kotlin/MethodInspector.kt
  src/main/resources/META-INF/plugin.xml
Labels: enhancement

#13 [feat] Write file to disk
  src/main/kotlin/MethodInspector.kt
Labels: enhancement

#14 [refac] Delete obsolete code and convert java to kotlin
  build.gradle
  src/main/java/PopupDialogAction.java
  src/main/kotlin/ExampleClassFourMethodsK.kt
  src/main/resources/META-INF/plugin.xml
Labels: refactor

#16 #10 show the number of lines in each Java method
  src/main/kotlin/MethodInspector.kt
Labels: enhancement

#18 Kotlin inspector
  build.gradle
  src/main/kotlin/MethodInspectorK.kt
  src/main/resources/META-INF/plugin.xml
Labels: enhancement

#23 #20 Cyclomatic Complexity pull request
  src/main/java/exampleClasses/ExampleClassJava.java
  src/main/kotlin/MethodInspector.kt
Labels: enhancement

#24 [refac] Updated the readme.
  README.md
Labels: documentation

#25 [doc] Correct the headers in the README
  README.md
Labels: documentation

#26 [refac] Reformat reports
  out/production/classes/ExampleClassFourMethodsK.class
  out/production/classes/ExampleClasses/ExampleClassFourMethods.class
  out/production/classes/META-INF/JetBrainsPlugin.kotlin_module
  out/production/classes/MethodInspector$actionPerformed$1.class
  out/production/classes/MethodInspector$actionPerformed$2.class
  out/production/classes/MethodInspector.class
  out/production/classes/MethodInspectorJ$inspectJavaFile$1.class
  out/production/classes/MethodInspectorJ$inspectKotlinFile$1.class
  out/production/classes/MethodInspectorJ$writeResult$1.class
  out/production/classes/MethodInspectorJ.class
  out/production/classes/MethodInspectorK$actionPerformed$1.class
  out/production/classes/MethodInspectorK$actionPerformed$2.class
  out/production/classes/MethodInspectorK.class
  out/production/resources/META-INF/plugin.xml
  src/main/kotlin/MethodInspector.kt
Labels: refactor
